// Included inside Smp::Fo4PhysicsWorld private section.
// Split from Fo4PhysicsWorld.h: private data members.

		std::mutex lock_;
		std::unique_ptr<AsyncStepState> asyncStepState_;
		std::unique_ptr<btDefaultCollisionConfiguration> collisionConfiguration_;
		std::unique_ptr<hdt::CollisionDispatcher> dispatcher_;
		std::unique_ptr<btBroadphaseInterface> broadphase_;
		std::unique_ptr<btConstraintSolverPoolMt> solver_;
		std::unique_ptr<btDiscreteDynamicsWorld> dynamicsWorld_;
		std::uint64_t candidateEvents_{ 0 };
		std::uint64_t simulationFrame_{ 1 };
		int maxSubSteps_{ 4 };
		float fixedStepSeconds_{ 1.0F / 60.0F };
		float averageInterval_{ 1.0F / 60.0F };
		float accumulatedInterval_{ 0.0F };
		float currentStepSeconds_{ 1.0F / 60.0F };
		bool useRealTime_{ false };
		float budgetMs_{ 3.5F };
		int sampleSize_{ 5 };
		std::uint32_t metricFrameInterval_{ 60 };
		std::uint32_t metricFrameCounter_{ 0 };
		float averageStepMs_{ 0.0F };
		float averageWritebackMs_{ 0.0F };
		float averageMainSyncMs_{ 0.0F };
		float averageStepReadMs_{ 0.0F };
		float averageStepWindMs_{ 0.0F };
		float averageStepBulletMs_{ 0.0F };
		float averageStepCollisionMs_{ 0.0F };
		float pendingWritebackMs_{ 0.0F };
		float pendingMainSyncMs_{ 0.0F };
		float pendingStepReadMs_{ 0.0F };
		float pendingStepWindMs_{ 0.0F };
		float pendingStepBulletMs_{ 0.0F };
		float pendingStepCollisionMs_{ 0.0F };
		std::uint32_t pendingStepCollisionCalls_{ 0 };
		std::uint32_t cellJobsWritebacks_{ 0 };
		std::uint32_t postAnimationWritebacks_{ 0 };
		std::uint32_t mainSyncWritebacks_{ 0 };
		std::uint32_t duplicateCellJobsWritebacks_{ 0 };
		std::uint32_t duplicatePostAnimationWritebacks_{ 0 };
		bool disabled_{ false };
		int solverIterations_{ 10 };
		float solverErp_{ 0.2F };
		bool clampRotations_{ true };
		float rotationSpeedLimit_{ 10.0F };
		bool unclampedResets_{ true };
		float unclampedResetAngle_{ 130.0F };
		bool disableFirstPersonViewPhysics_{ false };
		bool enableNpcPhysics_{ true };
		bool autoAdjustMaxActors_{ false };
		std::size_t maxActiveActors_{ 4 };
		std::size_t currentMaxActiveActors_{ 4 };
		float maxActorDistance_{ 3000.0F };
		bool windEnabled_{ false };
		bool windUseWeather_{ false };
		float windStrength_{ 0.0F };
		bool disableSMPHairWhenWigEquipped_{ true };
		float windDistanceForNoWind_{ 50.0F };
		float windDistanceForMaxWind_{ 3000.0F };
		float windWeatherCooldown_{ 0.0F };
		float windWeatherShortCooldownSeconds_{ 0.5F };
		float windWeatherLongCooldownSeconds_{ 5.0F };
		int windSmoothingSamples_{ 8 };
		bool randomizePerBoneWind_{ true };
		btVector3 windDirection_{ 1.0F, 0.0F, 0.0F };
		btVector3 currentWind_{ 0.0F, 0.0F, 0.0F };
		btVector3 targetWind_{ 0.0F, 0.0F, 0.0F };
		std::string prototypePhysicsXml_;
		std::vector<PrototypeActorState> prototypeActors_;
		std::vector<SuspendedActorCandidate> suspendedActors_;
		std::vector<PendingActorRebuild> pendingActorRebuilds_;
		std::vector<PendingHeadRebuild> pendingHeadRebuilds_;
		std::uint32_t characterCustomizationMenuDepth_{ 0 };
		RE::ActorHandle characterCustomizationTarget_;
		std::uint32_t characterCustomizationEditMode_{ 0 };
		bool characterCustomizationActorDirty_{ false };
		bool characterCustomizationHeadDirty_{ false };
		std::vector<PrototypeArmorRecord> characterCustomizationArmorRecords_;
		std::uint32_t loadingMenuDepth_{ 0 };
		bool loadingPhysicsSuspended_{ false };
		bool registered_{ false };
